### ISSUE TITLE
invalid option: --pygments

### ISSUE THREAD

**Issue by tjoozey** [tmm1/pygments.rb#113]
I'm trying to run 'rake generate' by using 'jekyll --pygments' and it's returning:

Deprecation: Jekyll now uses subcommands instead of just switches. Run `jekyll help' to find out more.
       Deprecation: The 'pygments' setting can only be set in your config files.
invalid option: --pygments
mv: rename site/atom.html to site/atom.xml: No such file or directory

> > > Site Generating Complete! <<<

Any way to fix this?

**Comment by slonopotamus** [comment]
Unfortunately, Jekyll dropped support for pygments.rb: https://github.com/jekyll/jekyll/pull/7118
