### ISSUE TITLE
JS syntax highlighter - Computed Property Names cause whole line to be hidden on some occasions

### ISSUE THREAD

**Issue by flaki** [tmm1/pygments.rb#115]
Came across a peculiar and hard-to track down bug with the JavaScript syntax highlighter: it seems that [ES6 Computed Property Name declarations](http://wiki.ecmascript.org/doku.php?id=harmony:object_literals#object_literal_computed_property_keys) inside object initializers seem to bug out the parser in certain situations, seemingly depending on the indentation used on the line of the declaration.

Some indent combination on such declarations cause the whole line to be skipped and rendered empty. See proof below:

``` JavaScript
// Indented with one tab
var onetab = {
    ["this_is"]: "visible"
}

// Indented with one tab and one space
var tabspace = {
     ["this_is"]: "visible"
}

// Indented with one space - fails
var onespace = {
 ["this_is"]: "hidden"
}

// Indented with two spaces - fails
var twospaces = {
  ["this_is"]: "hidden"
}

// Indented with three spaces - fails
var threespaces = {
   ["this_is"]: "hidden"
}

// Indented with four spaces
var fourspaces = {
    ["this_is"]: "visible"
}

// No indent - fails
var noindent = {
["this_is"]: "hidden"
}
```

This shows up on my machine (Windows 8 x64, Firefox Nightly) as the following:
![syntaxhighlighter](https://f.cloud.github.com/assets/2089432/2369228/1c7b44f8-a7d5-11e3-8289-9fbd48c54cb0.jpg)

Sections with no indentation, or indented with 1-3 spaces do not show up, and are hidden completely (HTML source of those lines is missing, also).

**Comment by slonopotamus** [comment]
Please, retest this with #205 included.
