### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by mrueg** [tmm1/pygments.rb#118]
# Running tests:

....................F...........................

Finished tests in 9.391907s, 5.1108 tests/s, 10.4345 assertions/s.

  1) Failure:
test_highlight_works_with_larger_files(PygmentsHighlightTest) [/var/tmp/portage/dev-ruby/pygments_rb-0.5.4-r1/work/ruby19/pygments.rb-0.5.4/test/test_pygments.rb:35]:
<455203> expected but was
<454107>.

48 tests, 98 assertions, 1 failures, 0 errors, 0 skips
rake aborted!

due to this commit:
https://github.com/tmm1/pygments.rb/commit/00e872a28480c1788aee43557cb4b2fab682deb5

How is the number generated there? I think it worked some day. Probably related to ruby version?

**Comment by gfx** [comment]
It has been fixed.
