### ISSUE TITLE
Update yajl-ruby dependency to ~>1.2.0

### ISSUE THREAD

**Issue by mrueg** [tmm1/pygments.rb#133]
It would be great to support latest yajl-ruby, too.

**Comment by jdickey** [comment]
I see the merge of PR #106 on `master`; any chance we can have a new release (0.6.1, perhaps) to make life easier for those of us who need that (e.g., to satisfy dependencies of our own internal Gems)?

**Comment by parkr** [comment]
This has been done and is released. Please close
