### ISSUE TITLE
Confusing error on Windows 'cannot close fd before spawn'

### ISSUE THREAD

**Issue by hickford** [tmm1/pygments.rb#137]
> cannot close fd before spawn

f03df350c253c12184b6262c6d1fbe869f83477a broke pygments.rb on Windows. That's upset several thousand Jekyll bloggers https://stackoverflow.com/questions/17364028/jekyll-on-windows-pygments-not-working

**Comment by janpapenbrock** [comment]
Any news on this?

**Comment by hickford** [comment]
@tnm @tmm1 this is vital issue for windows users

**Comment by tmm1** [comment]
I've released version 0.6.3 to rubygems.

**Comment by hickford** [comment]
Wahey thanks
