### ISSUE TITLE
JavaScript Template Strings highlighted as errors.

### ISSUE THREAD

**Issue by isiahmeadows** [tmm1/pygments.rb#140]
The following should be highlighted as syntactically correct template strings:

``` js
`foo`  // equivalent to "foo"
`foo${bar}`  // equivalent to "foo" + bar
`f${oo}b${ar}`  // equivalent to "f" + oo + "b" + ar
`${foo}${bar}`  // equivalent to foo + "" + bar
`${foo}`  // equivalent to foo + ""
```

When each string is highlighted as a template string (like CoffeeScript's or Ruby's double-quoted strings), then I know it's been patched for the site.

This is part of the ES6 proposal, already used in production.

**Comment by jledentu** [comment]
+1, the Javascript lexer should be fixed

**Comment by syymza** [comment]
+1

**Comment by rtoal** [comment]
Waiting for this too. Wish I had time to contribute.

**Comment by jawache** [comment]
Hia, is there some work around for this?

**Comment by gfx** [comment]
Released pygments.rb v1.0.0 with the latest Pygments 2.2.0-snapshot.

If you have more problems, please report issues to the upstream project: https://bitbucket.org/birkenfeld/pygments-main

This gem is just a binding to it.
