### ISSUE TITLE
Racket formatting incorrect for square brackets

### ISSUE THREAD

**Issue by zenspider** [tmm1/pygments.rb#141]
As seen here: https://github.com/mflatt/s3-sync/blob/master/main.rkt#L26-L33

The square brackets have the CSS class `pl-ii` which is applying a red color to it. Square brackets in racket (as with most lisps) are just another form of paren and should be treated the same as regular `()`.

I tried to track it down in pygments.rb, but I'm not familiar enough with the code to see anything wrong with the racket code. Point me in the right direction and I can try to do a PR.

**Comment by slonopotamus** [comment]
Please, retest this after #205.
