### ISSUE TITLE
Clojure: allowed unicode characters highlighted as errors

### ISSUE THREAD

**Issue by siefca** [tmm1/pygments.rb#142]
In Clojure it is possible to create symbols containing unicode word-class characters, e.g.:

``` clojure
(rok-przestępny? 2000)
```

Here: Polish letter 'eogonek' (latin small letter E with ogonek) causes this character to be marked as error.

**Comment by gfx** [comment]
Please report the upstream project: https://bitbucket.org/birkenfeld/pygments-main

This gem is just a binding to it.
