### ISSUE TITLE
CHANGELOG does not reflect changes for 0.6.0

### ISSUE THREAD

**Issue by TALlama** [tmm1/pygments.rb#143]
Please help us out by letting us know what changed. Looking at [the diff](https://github.com/tmm1/pygments.rb/compare/v0.5.4...v0.6.0), my rookie eyes see:
- Updated to latest version of pygments
- Allow setting a custom timeout by setting `ENV['MENTOS_TIMEOUT']`
- Cache lexers for better performance
- Fixed an issue where TOML might not be recognized properly
- Made it clear what license the project uses

**Comment by parkr** [comment]
@TALlama Can you submit a PR? They're easier to deal with.
