### ISSUE TITLE
Ruby comment highlighting broken

### ISSUE THREAD

**Issue by weaksauce** [tmm1/pygments.rb#144]
expect this to highlight the embedded string interpolation as tokens instead of the first # sign commenting out the rest of the line. 

``` ruby
desc "Show off the API"
  task :ditty do
    on roles(:all) do |host|
      # Capture output from the remote host, and re-use it
      # we can reflect on the `host` object passed to the block
      # and use the `info` logger method to benefit from the
      # output formatter that is selected.
      uptime = capture('uptime')
      if host.roles.include?(:web)
        info "Your webserver #{host} has uptime: #{uptime}"
      end
    end

  end
```

on github pages the default version of this gem is 0.6.0 and the problem exists there. you can see it live on http://capistranorb.com/documentation/overview/what-is-capistrano/ at the bottom of the page. 

interestingly enough it's handled correctly on the above code.

**Comment by tmm1** [comment]
This is likely an upstream issue in pygments itself, and should be reported against that project.

**Comment by weaksauce** [comment]
pygments is working actually: http://pygments.org/demo/1089661/

the latest version of pygments is 2.0.1 and this gem uses 1.7 

are there any breaking changes that would stop an upgrade to 2.0.1?
