### ISSUE TITLE
Please merge 1-line show-stopping bug fix

### ISSUE THREAD

**Issue by FranklinChen** [tmm1/pygments.rb#145]
I've been frustrated for 6 months that a 1-line bug fix I submitted has not yet been merged, despite another version of the gem just being released today. This bug causes me to have to manually edit gems/pygments.rb-0.6.1/lib/pygments/popen.rb just to be able to use Octopress. I've tried not to repeatedly complain about this, knowing that people are busy, but am confused about why this bug fix has not been accepted yet.

https://github.com/tmm1/pygments.rb/pull/132

**Comment by tmm1** [comment]
I've published 0.6.2 with this fix.
