### ISSUE TITLE
Adding a new syntax - build fails

### ISSUE THREAD

**Issue by wolandscat** [tmm1/pygments.rb#148]
I would like to add a new syntax definition according to [this documentation](http://pygments.org/docs/lexerdevelopment/).

I have pygments.rb installed under cygwin, and it is working (asciidoctor uses it).

I should be able to do this, according to the info above:

```
$ cd pygments-main
$ make mapfiles
```

This fails - here is what I get:

```
$ make mapfiles
(cd pygments/lexers; python _mapping.py)
pygments.lexers.agile
pygments.lexers.asm
pygments.lexers.compiled
pygments.lexers.dalvik
pygments.lexers.dotnet
pygments.lexers.foxpro
pygments.lexers.functional
pygments.lexers.github
pygments.lexers.graph
pygments.lexers.hdl
pygments.lexers.inferno
pygments.lexers.jvm
pygments.lexers.math
pygments.lexers.other
pygments.lexers.parsers
pygments.lexers.qbasic
pygments.lexers.rdf
pygments.lexers.shell
pygments.lexers.special
pygments.lexers.sql
pygments.lexers.templates
pygments.lexers.text
pygments.lexers.web
(cd pygments/formatters; python _mapping.py)
Traceback (most recent call last):
  File "_mapping.py", line 35, in <module>
    from pygments.formatters.other import TestcaseFormatter
ImportError: cannot import name TestcaseFormatter
Makefile:43: recipe for target 'mapfiles' failed
make: *** [mapfiles] Error 1
```

I have ruby 2.2.2 and pygments.rb-0.6.3.

Any ideas? (Note: I'm not a python or ruby developer).

**Comment by tmm1** [comment]
New syntax must be submitted upstream to the Python project. This is just a
ruby wrapper.

**Comment by wolandscat** [comment]
I understand that, but would you expect the build to work or not, i.e. is the pygments.rb gem a completely copy of the important parts of the original project? It seems to be, which is why I asked the question.

**Comment by wolandscat** [comment]
This problem is reported at the [pygments Bitbucket site](https://bitbucket.org/birkenfeld/pygments-main/issue/986/support-for-elm-language).

A new drop of the pygments code into pygments.rb will fix this.
