### ISSUE TITLE
Do I need to run `pip install pygments` to install/use this gem?

### ISSUE THREAD

**Issue by i-give-up** [tmm1/pygments.rb#155]
I see [here](https://github.com/tmm1/pygments.rb/tree/master/vendor/pygments-main) that pygments.rb already ships with its own copy of the python module.

But it says [on this guide for setting up Jekyll on Windows](http://jekyll-windows.juthilo.com/3-syntax-highlighting/) that you need to install the python module first to use this gem.

I want to double check with you before contacting the guide's maintainer about this.

**Comment by mxm** [comment]
No, you don't have to. Pygments is shipped with pygments.rb.
