### ISSUE TITLE
Update pygments-main

### ISSUE THREAD

**Issue by tpluscode** [tmm1/pygments.rb#160]
Hi. Is there any chance for pygments 2.1+?

**Comment by Quramy** [comment]
👍

**Comment by ckruse** [comment]
Is this gem dead?

**Comment by rumpelsepp** [comment]
@tmm1 Please update it.

**Comment by gfx** [comment]
Upgraded by https://github.com/tmm1/pygments.rb/pull/167.

Released pygments.rb v1.0.0 with Pygments 2.2.0-snapshot.

**Comment by ckruse** [comment]
Thanks!
