### ISSUE TITLE
Elm syntax highlighting

### ISSUE THREAD

**Issue by BrianHicks** [tmm1/pygments.rb#169]
I'd like to use Elm syntax highlighting for a book I'm writing with Softcover (relevant issue: https://github.com/softcover/softcover/issues/173.) It looks like the trail of breadcrumbs leads here, would it be possible to release an updated version with Elm support? It looks like Pygments supports it in a released version now.

**Comment by gfx** [comment]
This gem is just a wrapper to [Pygments](http://pygments.org/), a syntax highlighter written in Python.

Tell your problem to the upstream project.

**Comment by gfx** [comment]
Oops, sorry, I misunderstood.

pygments.rb v1.0.0 bundles Pygments 2.2.0-snapshot. Check it out.
