### ISSUE TITLE
Mapping for turtle lexer missing in lexers cache file

### ISSUE THREAD

**Issue by jechterhoff** [tmm1/pygments.rb#175]
Hello,

Please update the lexers cache file to include a mapping for the turtle lexer.

Background: I'm writing an asciidoc document that contains source examples in Turtle (https://www.w3.org/TR/turtle/). Pygments supports highlighting for Turtle. However, when converting the document to html using asciidoctor (which uses pygments.rb) the Turtle examples are not highlighted. I've already filed an issue with asciidoctor, including an example, and it turned out that the missing mapping of the turtle lexer in pygments.rb was the cause. For details, see https://github.com/asciidoctor/asciidoctor/issues/2001 That issue is now closed, since a workaround is available. I created this issue so that the workaround will hopefully no longer be required after the next release of pygments.rb.

**Comment by gfx** [comment]
Done by #180
