### ISSUE TITLE
Liquid Exception in markdown format

### ISSUE THREAD

**Issue by raghavgujjar** [tmm1/pygments.rb#188]
Liquid Exception: Exec format error - C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pygments.rb-1.2.1/lib/pygments/mentos.py

This is my markdown file: https://github.com/raghavgujjar/raghavgujjar.github.io/blob/source/source/_posts/2016-05-21-distilling-the-essence-of-async-tasks-in-javascript.md

It doesn't seem to like the syntax: `{% highlight javascript} {% highlight %}` anymore. With `>=0` version it wasn't a problem. Please suggest an alternative.

**Comment by slonopotamus** [comment]
I believe, you just need to install Python and make sure either `py` or `python` is in PATH.
