### ISSUE TITLE
Becoming a maintainer

### ISSUE THREAD

**Issue by slonopotamus** [tmm1/pygments.rb#197]
Hi there!

I'm kinda disappointed with current level of activity on pygments.rb project and would like to give it some more traction. PRs seem not to work (#194 with Python 3 support is almost half a year old).

pygments.rb is used downstream by several projects and as a maintainer of one of them, I would like to see pygments.rb in a more healthy state. I do understand that @tmm1 and @gfx might not have enough time they can dedicate to this project, so I offer my hands.

So, my offering is: you add me as a developer to pygments.rb, I merge PRs, make releases, etc. There is other alternative - someone can make a fork of pygments.rb and downstream projects switch to it, but I would like to avoid this scenario if possible.

My background: primarily, Java/C++ programmer with 15+ years experience. Able to read some 10th of other programming languages. Using both Windows and Linux on a daily basis.

Maintaining [git-as-svn](https://github.com/bozaro/git-as-svn) and [Asciidoctor EPUB3](https://github.com/asciidoctor/asciidoctor-epub3) FOSS projects.

GitHub says I did 1.1k commits last year. I'd say this is a moderate OSS contribution activity.

**Comment by gfx** [comment]
+1

@tmm1 Also, I would make a GitHub organization to maintain this project, since personal repositories cannot grant admin permissions to other members.

**Comment by tmm1** [comment]
I am not using this project and would welcome new maintainership. Let me know which organization to transfer the repository to.

**Comment by slonopotamus** [comment]
I've opened an issue in pygments, possibly they will agree to move pygments.rb into their organization: https://github.com/pygments/pygments/issues/1660

**Comment by slonopotamus** [comment]
@tmm1 Could you please disable CircleCI build for this repo?

**Comment by slonopotamus** [comment]
@tmm1 Also, please add me to RubyGems so I can do releases. Email: marat@slonopotamus.org

**Comment by slonopotamus** [comment]
@tmm1 please, coordinate with pygments devs on repo transfer in pygments/pygments#1660. And I still need you to add me to pygments.rb on rubygems.org, so I can publish releases.

**Comment by slonopotamus** [comment]
Confirming that I got access to rubygems.org. Closing this issue, since there's nothing to do here anymore. Transfer is handled by pygments/pygments#1660
