### ISSUE TITLE
Lexers are loaded in random order

### ISSUE THREAD

**Issue by cjohansen** [tmm1/pygments.rb#41]
It seems that the Lexers are loaded in random order. In my test, I get occasional failures when highlighting a `.txt` file, depending on which was loaded into Pygments.rb last: "Text only" (most of the time) or CMake (occasionally). This produces some truly bizarre behavior. Is it possible to make the lexer ordering deterministic?

**Comment by slonopotamus** [comment]
I cannot reproduce it with current `master` branch.
