### ISSUE TITLE
Syntax Highlighting doesn't work on `<code>` tags inside `<pre>` tags

### ISSUE THREAD

**Issue by marcamillion** [tmm1/pygments.rb#68]
I may be doing something wrong, but the syntax is being highlighted on `<code>` tags that are not within `<pre>` tags in my app.

In other words, this works:

`<code>std::sort(data, data + arraySize);</code>`

But, this doesn't:

`<pre class="lang-cpp prettyprint-override">
<code>#include &lt;algorithm&gt; #include &lt;ctime&gt; #include &lt;iostream&gt; int main()</code>
</pre>`

How do I fix this? Is this an issue you guys are aware of?

Is there a workaround?

Thanks.

**Comment by slonopotamus** [comment]
Pygments version was updated in #205, please retest.
