### ISSUE TITLE
Add Stylus lexer

### ISSUE THREAD

**Issue by yoshuawuyts** [tmm1/pygments.rb#75]
It would be awesome to have support for [Stylus](https://github.com/learnboost/stylus). A duplicate issue has been opened on the [Stylus issue page](https://github.com/LearnBoost/stylus/issues/1031).

**Comment by acidjazz** [comment]
What ever came of this?

**Comment by Zolmeister** [comment]
+1

**Comment by yoshuawuyts** [comment]
it's been a while, closing
