### ISSUE TITLE
utf-8 on windows

### ISSUE THREAD

**Issue by robert-hoffmann** [tmm1/pygments.rb#96]
Hi,

Jekyll on windows breaks. This has been tracked to pygments > 0.5.0 breaking, see here https://github.com/mojombo/jekyll/pull/1487#issuecomment-27040718

Any ideas or updates to this, since building github pages on windows is probably something many people want to do, and utf-8 (at least for me) has pretty much become standard as far as generating internationalized files go (actually i just utf-8 EVERYTHING ..html, js, txt, css).

Thanks,
Robert

**Comment by slonopotamus** [comment]
Unfortunately, Jekyll dropped pygments.rb support: https://github.com/jekyll/jekyll/issues/6823
