### ISSUE TITLE
jRuby compatibility

### ISSUE THREAD

**Issue by hiravgandhi** [tmm1/pygments.rb#99]
POSIX::Spawn causes issues with the latest version of jRuby. Is there a way to remove this dependency  or alter it for jRuby so that it is not needed?

**Comment by mojavelinux** [comment]
For reference, if you install the following gem:

```
$ gem install pygments.rb-jruby
```

Then replace the call to popen4 as @bartkamphorst suggested:

```ruby
require 'open3' if RUBY_ENGINE == 'jruby'

...

@in, @out, @err, @wait = Open3.popen3(script)
@pid = @wait[:pid]
```

Then it works. Of course, that's an older version of the gem ;(

**Comment by mojavelinux** [comment]
I put together a pull request that implements these changes. I'm happy to say it works as expected!
